language: objective-c
osx_image: xcode8
before_install:
  - sudo gem install cocoapods --pre
script: xctool -workspace maccha.xcworkspace -scheme maccha build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
